nrccua/aioradio

- HISTORY.rst
- aioradio/logger.py
- setup.py
v0.9.0 (2020-11-17)
* Set logger.propogate to False after adding handler.
* Remove use_ddtrace logic from DatadogLogger.
> Improving DatadogLogger

- HISTORY.rst
- aioradio/aws/s3.py
- aioradio/file_ingestion.py
- aioradio/tests/s3_test.py
- setup.py
v0.9.3 (2020-12-03)
* Add functions (get_ftp_file_attributes & get_s3_file_attributes) to retrieve metadata on files in FTP and S3.
> Adding ability to get ftp & s3 file attributes

- .pre-commit-config.yaml
- HISTORY.rst
- aioradio/aws/dynamodb.py
- aioradio/aws/moto_server.py
- aioradio/aws/s3.py
- aioradio/aws/secrets.py
- aioradio/aws/sqs.py
- aioradio/aws/utils.py
- aioradio/file_ingestion.py
- aioradio/jira.py
- aioradio/logger.py
- aioradio/pyodbc.py
- aioradio/redis.py
- aioradio/requirements.txt
- aioradio/tests/aws_secrets_test.py
- aioradio/tests/dynamodb_test.py
- aioradio/tests/file_ingestion_test.py
- aioradio/tests/jira_test.py
- aioradio/tests/logger_test.py
- aioradio/tests/pyodbc_test.py
- aioradio/tests/redis_test.py
- aioradio/tests/s3_test.py
- aioradio/tests/sqs_test.py
- conftest.py
- setup.py
v0.9.6 (2020-12-22)
* Apply pydoc to repository.
* Add isort and docformatter to pre-commit.
> apply pydoc to project

- HISTORY.rst
- aioradio/aws/dynamodb.py
- aioradio/aws/secrets.py
- aioradio/aws/sqs.py
- aioradio/aws/utils.py
- aioradio/tests/aws_secrets_test.py
- aioradio/tests/dynamodb_test.py
- aioradio/tests/sqs_test.py
- setup.py
v0.9.8 (2021-02-01)
* Add ability to add more regions besides us-east-1 & us-east-2.
> Add option for adding more regions.

- HISTORY.rst
- aioradio/redis.py
- aioradio/tests/pyodbc_test.py
- aioradio/tests/redis_test.py
- setup.py
v0.11.0 (2021-02-18)
* Add initial support in redis for the hashes data structure.
> Adding hashes in redis

- HISTORY.rst
- aioradio/redis.py
- aioradio/tests/redis_test.py
- setup.py
v0.11.1 (2021-02-18)
* Fix issue with sending None values in redis func hmget.
> fix bug with redis function hmget

- HISTORY.rst
- aioradio/redis.py
- aioradio/tests/redis_test.py
- setup.py
v0.11.2 (2021-02-18)
* Add custom hmget_many & hmgetall_many redis commands to get many hashed keys data.
> Adding ability to get many hashed key values

- HISTORY.rst
- aioradio/redis.py
- setup.py
v0.11.4 (2021-02-22)
* Use redis transactions via pipelining with hash set & expire commands.
> pipeline some redis cmds

- HISTORY.rst
- aioradio/file_ingestion.py
- aioradio/pyodbc.py
- aioradio/redis.py
- aioradio/requirements.txt
- aioradio/utils.py
- setup.py
v0.11.6 (2021-03-01)
* Simplify manage_async_tasks args to include list of coroutines.
> Adding async utils script

- HISTORY.rst
- README.md
- aioradio/redis.py
- aioradio/requirements.txt
- aioradio/tests/redis_test.py
- conftest.py
- setup.py
v0.12.0 (2021-03-08)
* Use aioredis transactions performance fixed branch (sean/aioredis-redis-py-compliance) instead of version 1.3.1.
> Arch 563 use performance improved aioredis branch for trans

- .pre-commit-config.yaml
- HISTORY.rst
- aioradio/long_running_jobs.py
- aioradio/requirements.txt
- aioradio/tests/long_running_jobs_test.py
- conftest.py
- setup.py
v0.13.1 (2021-04-13)
* Updating LongRunningJob to use either 'sqs' or 'redis' as the queue mechanism.
> Adding redis and sqs as queue to LongRunningJobs

- HISTORY.rst
- Makefile
- aioradio/long_running_jobs.py
- aioradio/tests/long_running_jobs_test.py
- conftest.py
- setup.py
v0.13.2 (2021-04-13)
* Add ability for LongRunningJobs to run one to many jobs.
> LongRunningJobs can run one to many jobs

- HISTORY.rst
- aioradio/long_running_jobs.py
- setup.py
v0.13.3 (2021-04-13)
* Fix issue with pulling more than one message in LongRunningJobs.
> Fix max messages issue

- .github/workflows/.pre-commit.yaml
- HISTORY.rst
- Makefile
- aioradio/long_running_jobs.py
- aioradio/redis.py
- aioradio/requirements.txt
- aioradio/tests/file_ingestion_test.py
- aioradio/tests/long_running_jobs_test.py
- aioradio/tests/psycopg2_test.py
- aioradio/tests/pyodbc_test.py
- conftest.py
- setup.py
v0.13.4 (2021-04-22)
* Remove sensitive company emails and database references.
> Remove sensitive company emails and database refs

- HISTORY.rst
- aioradio/pyodbc.py
- setup.py
v0.13.8 (2021-06-02)
* Add application_intent & tds_version as pyodbc connection options.
> Add application_intent & tds_version as pyodbc connection options

- HISTORY.rst
- Makefile
- aioradio/aws/utils.py
- aioradio/requirements.txt
- aioradio/tests/file_ingestion_test.py
- setup.py
v0.13.12 (2021-06-09)
* Remove logging in aioradio/aws/utils.py.
* Skip all tests interacting with FTP.
> Ds 78 remove logging in aws utils py

- HISTORY.rst
- Makefile
- aioradio/long_running_jobs.py
- setup.py
v0.13.13 (2021-06-10)
* Add callback_url functionality in long_running_jobs.
> Add callback_url functionality in long_running_jobs

- HISTORY.rst
- Makefile
- aioradio/requirements.txt
- setup.py
v0.13.15 (2021-07-21)
* Update aiobotocore==1.2.2.
> downgrade aiobotocore version to 1.2.2

- HISTORY.rst
- aioradio/long_running_jobs.py
- setup.py
v0.13.18 (2021-07-21)
* Use json instead of data for callback.
> Use json instead of data for callback

- HISTORY.rst
- aioradio/file_ingestion.py
- setup.py
Updated check_date and check_year function that now use constants to check min/max values.
> Efi check date defaults

- HISTORY.rst
- aioradio/file_ingestion.py
- setup.py
v0.16.1 (2022-01-13)
* Adding UniqueID as new el3 field, in place of StudentID
* Removed logic for parsing phones numbers and text message opt in.
> Adding UniqueID as new el3 field

- HISTORY.rst
- aioradio/ds_utils.py
- setup.py
v0.17.2 (2022-02-18)
* Adding converted async to sync functions to ds_utils.py.
> Adding converted async to sync funcs to ds_utils

- HISTORY.rst
- aioradio/requirements.txt
- setup.py
v0.17.3 (2022-02-18)
* Use dominodatalab installed from pypi instead of github.
> Use dominodatalab installed from pypi

- HISTORY.rst
- aioradio/ds_utils.py
- setup.py
v0.17.7 (2022-05-03)
* Add update_secret function to ds_utils.
> Add update_secret function to ds_utils

- HISTORY.rst
- aioradio/file_ingestion.py
- setup.py
v0.17.12 (2022-08-29)
* Add missing EL3 fields to file_injestion.py.
> Add missing EL3 fields

- HISTORY.rst
- setup.py
v0.17.15 (2022-09-15)
* Add python backoff library to install_requires in setup.
> Add backoff to install_requires in setup

- HISTORY.rst
- Makefile
- aioradio/requirements.txt
- setup.py
v0.17.17 (2022-10-01)
* Fixed botocore version to 1.27.59.
> Fixed botocore==1.27.59

- HISTORY.rst
- aioradio/file_ingestion.py
- aioradio/requirements.txt
- setup.py
v0.17.18 (2022-10-21)
* Add a function in file_ingestion to convert an xlsx file to csv/tsv.
* Update fakeredis==1.9.4.
* Update pylint==2.15.4.
> Add a function in file_ingestion to convert an xlsx file to csv/tsv

- HISTORY.rst
- aioradio/file_ingestion.py
- setup.py
v0.17.19 (2022-10-28)
* Update xlsx_to_tsv function to use s3 instead of local directories for origin/destination files.
> Update xlsx_to_tsv function to use s3

- HISTORY.rst
- aioradio/aws/sqs.py
- setup.py
v0.17.23 (2022-11-30)
* Add account_id argument to SQS functions for cross account functionality.
> Add ability to convey account id in sqs funcs

- HISTORY.rst
- aioradio/aws/secrets.py
- aioradio/file_ingestion.py
- aioradio/requirements.txt
- aioradio/tests/aws_secrets_test.py
- conftest.py
- setup.py
v0.17.26 (2023-01-12)
* Add option to pass aws_creds argument in get_secret function.
* Update httpx==0.23.3.
* Update orjson==3.8.5.
> Add option to pass aws_creds argument in get_secret function

- .pre-commit-config.yaml
- HISTORY.rst
- aioradio/file_ingestion.py
- aioradio/long_running_jobs.py
- aioradio/requirements.txt
- aioradio/tests/pyodbc_test.py
- setup.py
v0.17.27 (2023-01-20)
* Raise errors instead of printing in file_ingestion function zipfile_to_tsv.
* Update dominodatalab==1.2.2.
* Update pysmb==1.2.9.1.
> Raise errors instead of printing in file_ingestion function zipfile_to_tsv

- HISTORY.rst
- aioradio/long_running_jobs.py
- aioradio/tests/long_running_jobs_test.py
- setup.py
v0.17.29 (2023-01-31)
* Update sleep time from 30 to 5 seconds in long running jobs after exception.
* Refactor long running jobs to no longer use redis queue.
> Ds 353 update sleep time in long running jobs after excep

- HISTORY.rst
- aioradio/aws/moto_server.py
- aioradio/long_running_jobs.py
- aioradio/requirements.txt
- setup.py
v0.17.30 (2023-02-03)
* Update LongRunningJobs to gracefully deal with exceptions during narwhal execution.
* Update aioboto3==10.4.0.
* Update openpyxl==3.1.0.
> Update LongRunningJobs to gracefully deal with exceptions

- .pre-commit-config.yaml
- HISTORY.rst
- aioradio/file_ingestion.py
- setup.py
v0.17.32 (2023-02-03)
* Update csv sniffer to read 8192 bytes instea of 4096.
> Update csv sniffer to read 8192 bytes instea of 4096

- HISTORY.rst
- aioradio/requirements.txt
- setup.py
v0.17.33 (2023-02-14)
* Hardcode openpyxl version to 3.0.10.
> Hardcode openpyxl version to 3.0.10

- HISTORY.rst
- aioradio/file_ingestion.py
- setup.py
v0.17.34 (2023-02-16)
* Revise ethnicity check in EFI and increase truncation limit.
> Revise ethnicity check in EFI and increase truncation limit

- HISTORY.rst
- aioradio/file_ingestion.py
- aioradio/tests/file_ingestion_test.py
- setup.py
v0.17.35 (2023-02-23)
* Create function check_phone_number in efi parsing.
* Update bytes read in detect_delimiter function from 4096 to 8192.
> Create function check_phone_number in efi parsing

- HISTORY.rst
- aioradio/file_ingestion.py
- setup.py
v0.17.36 (2023-03-13)
* Raise error instead of printing in file_ingestion function xlsx_to_tsv.
> Raise error instead of printing in file_ingestion function xlsx_to_tsv

- HISTORY.rst
- aioradio/ds_utils.py
- aioradio/file_ingestion.py
- aioradio/requirements.txt
- setup.py
v0.18.2 (2023-04-18)
* Add psycopg2 imports inside functions and not at the top of the file.
> Add psycopg2 imports inside functions

- HISTORY.rst
- Makefile
- aioradio/file_ingestion.py
- aioradio/tests/file_ingestion_test.py
- setup.py
v0.18.3 (2023-06-07)
* Add excel sheet filter to file ingestion efi functions.
> Add excel sheet filter to file ingestion efi functions

- HISTORY.rst
- aioradio/ds_utils.py
- setup.py
v0.19.1 (2023-09-07)
* Set logging level in ds_utils.
> Set logging level in ds_utils

- HISTORY.rst
- aioradio/ds_utils.py
- aioradio/requirements.txt
- aioradio/tests/dynamodb_test.py
- aioradio/tests/sqs_test.py
- conftest.py
- setup.py
v0.20.6 (2023-12-14)
* Add stage_table optional argument to merge_spark_df_in_db ds.utils function.
* Update aioboto3==12.1.0.
* Update boto3==1.33.1.
* Update botocore==1.33.1.
> Add stage_table optional argument to merge_spark_df_in_db ds.utils func

- HISTORY.rst
- aioradio/ds_utils.py
- setup.py
v0.20.12 (2024-03-12)
* Avoid instantiating spark if databricks-connect installed.
> Avoid instantiating spark if databricks-connect installed

- HISTORY.rst
- aioradio/ds_utils.py
- setup.py
v0.20.13 (2024-03-15)
* Use spark df.toPandas() function instead of private function converted spark df -> pandas -> polars.
> Use spark df.toPandas() function instead of private function

- HISTORY.rst
- aioradio/ds_utils.py
- setup.py
v0.20.14 (2024-03-15)
* Fix bug with spark not being instantiated.
> Fix bug with spark not being instantiated

- HISTORY.rst
- aioradio/ds_utils.py
- setup.py
v0.20.17 (2024-04-05)
* Improve logging spark merge query results using logger instead of show.
> Improve logging spark merge query results using logger

- HISTORY.rst
- aioradio/ds_utils.py
- setup.py
v0.20.18 (2024-04-06)
* Add all variations of env names to ds_utils databricks catalog functions.
> Add all variations of env names to ds_utils databricks catalog functions

- HISTORY.rst
- aioradio/requirements.txt
- setup.py
v0.20.24 (2024-07-26)
* Update install require numpy==1.23.5.
> Update install require numpy==1.23.5

- HISTORY.rst
- aioradio/ds_utils.py
- aioradio/requirements.txt
- setup.py
v0.21.3 (2025-01-13)
* Update spark/polars functions to use arrow for better memory performance with databricks runtime 16.1+.
> Update spark/polars functions to use arrow

- HISTORY.rst
- aioradio/ds_utils.py
- setup.py
v0.21.9 (2025-03-20)
* Replace when_matched_update with when_matched_update_all adding exclude_cols parameter.
> Ds 601 replace when matched update with when matched upda
